before_script:
  - docker info
  - echo "build $CI_COMMIT_REF_NAME"
  - env | grep CI_
  - git version

# after_script:
#   - echo "build done"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "test" || $CI_COMMIT_REF_NAME == "release" || $CI_COMMIT_REF_NAME =~ /^sprint/
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    # - if: $CI_COMMIT_REF_NAME == "feat/ci" # test ci only
    #   when: always
    - when: never

stages:
  - build

build-tags:
  stage: build
  script:
    - echo "build tag"
  only:
    - tags

build:
  stage: build
  script:
    - echo "build image"
  after_script:
    - echo "clean build"
