# permissions for end users to view dbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: db-viewer-role
rules:
- apiGroups:
  - db.qucheng.io
  resources:
  - dbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.qucheng.io
  resources:
  - dbs/status
  verbs:
  - get
