# permissions for end users to view dbbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbbackup-viewer-role
rules:
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - dbbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - dbbackups/status
  verbs:
  - get
