# permissions for end users to edit dbbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbbackup-editor-role
rules:
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - dbbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - dbbackups/status
  verbs:
  - get
