# permissions for end users to view dbservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbservice-viewer-role
rules:
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - dbservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - dbservices/status
  verbs:
  - get
