# permissions for end users to view globaldbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globaldb-viewer-role
rules:
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - globaldbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - globaldbs/status
  verbs:
  - get
