# permissions for end users to edit globaldbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globaldb-editor-role
rules:
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - globaldbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - globaldbs/status
  verbs:
  - get
