# permissions for end users to edit restores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restore-editor-role
rules:
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - restores/status
  verbs:
  - get
