---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - dbbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - dbbackups/finalizers
  verbs:
  - update
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - dbbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - globaldbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - globaldbs/finalizers
  verbs:
  - update
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - globaldbs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - restores/finalizers
  verbs:
  - update
- apiGroups:
  - qucheng.easycorp.io
  resources:
  - restores/status
  verbs:
  - get
  - patch
  - update
