apiVersion: qucheng.easycorp.io/v1beta1
kind: Db
metadata:
  name: db-sample
spec:
  dbName: db-sample
  targetService: 
    name: db-sample
    namespace: cne-system
    port: 3306
  account:
    user:
      value: customuser
    password:
      value: custompassword
