# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/qucheng.easycorp.io_dbservices.yaml
- bases/qucheng.easycorp.io_dbs.yaml
- bases/qucheng.easycorp.io_backups.yaml
- bases/qucheng.easycorp.io_restores.yaml
- bases/qucheng.easycorp.io_globaldbs.yaml
- third_party/velero_resticrepositories.yaml
- bases/qucheng.easycorp.io_dbbackups.yaml
- bases/qucheng.easycorp.io_dbrestores.yaml
- bases/qucheng.easycorp.io_deletebackuprequests.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_dbservices.yaml
#- patches/webhook_in_dbs.yaml
#- patches/webhook_in_backups.yaml
#- patches/webhook_in_restores.yaml
#- patches/webhook_in_globaldbs.yaml
#- patches/webhook_in_dbbackups.yaml
#- patches/webhook_in_dbrestores.yaml
#- patches/webhook_in_deletebackuprequests.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_dbservices.yaml
#- patches/cainjection_in_dbs.yaml
#- patches/cainjection_in_backups.yaml
#- patches/cainjection_in_restores.yaml
#- patches/cainjection_in_globaldbs.yaml
#- patches/cainjection_in_dbbackups.yaml
#- patches/cainjection_in_dbrestores.yaml
#- patches/cainjection_in_deletebackuprequests.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
