name: install
on:
  push:
    branches:
      - master
    paths:
      - '**.go'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install kind
        uses: helm/kind-action@v1.3.0
        with:
          config: hack/kind/kind.yaml
      - name: install kubectl
        uses: azure/setup-kubectl@v3.0
      - name: install helm
        uses: azure/setup-helm@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GH_TOKEN }}
      - name: Cache Go Dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Install GoTools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2
          go install github.com/google/addlicense@latest
          go install golang.org/x/tools/cmd/goimports@latest
      - name: Install CNE Operator
        run: |
          make local
          kubectl apply -f hack/deploy/deploy.yaml
      - name: Check Status
        run: |
          kubectl get pods -n cne-system
